### ISSUE TITLE
Make nighttime more evident

### ISSUE THREAD

**Issue by sprkrd** [Lux-AI-Challenge/LuxViewer2021#24]
Currently the only indicator of nighttime is the little moon at the bottom of the screen. It would be much more visually clear to, in addition to that, change the background to a darker one, for instance.

**Comment by StoneT2000** [comment]
This is in the works! (You can see that our website has some of the night themed art already :) )

**Comment by StoneT2000** [comment]
after design discussion, potentially overlay 2nd layer of textures and tune opacity.
